name: Run Cursecatcher

on:
    schedule:
      - cron: "0 13 * * *"
    workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-venv python3-dev build-essential tzdata pkg-config cron

      - name: Set up virtual environment
        run: |
          python3 -m venv env
          source env/bin/activate
          pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt
    
      - name: Load secrets into environment
        run: |
          echo "GMAIL_EMAIL=${{ secrets.GMAIL_EMAIL }}" >> $GITHUB_ENV
          echo "GMAIL_APP_PASSWORD=${{ secrets.GMAIL_APP_PASSWORD }}" >> $GITHUB_ENV
          echo "CVSS_CUTOFF_SCORE=${{ secrets.CVSS_CUTOFF_SCORE }}" >> $GITHUB_ENV
          echo "NIST_KEY=${{ secrets.NIST_KEY }}" >> $GITHUB_ENV
          echo "BCC_LIST=${{ env.BCC_LIST }}" >> $GITHUB_ENV

      - name: Run main.py
        run: |
          source env/bin/activate
          python3 main.py